name: On-demand Unlighthouse

on:
  workflow_dispatch:
    inputs:
      SITE_URL:
        description: 'Site URL to scan'
        required: true
        type: string
      NETLIFY_SITE_ID:
        description: 'Netlify Site ID'
        required: true
        type: string

jobs:
  unlighthouse-scan-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install @unlighthouse/cli puppeteer

      - name: Run Unlighthouse scan
        run: npx unlighthouse-ci --site ${{ inputs.SITE_URL }} --build-static

      - name: Deploy report to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './.unlighthouse'
          production-branch: main
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy Unlighthouse report from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ inputs.NETLIFY_SITE_ID }}
        timeout-minutes: 5
