name: Unlighthouse assertions and static report

on:
  workflow_call:
    inputs:
      unlighthouse_config_file:
        required: true
        type: string
    secrets:
      NETLIFY_AUTH_TOKEN:
        required: true
      NETLIFY_SITE_ID:
        required: true

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install -g @unlighthouse/cli puppeteer netlify-cli

      - name: Run Unlighthouse scan
        run: unlighthouse-ci --config-file ${{ inputs.unlighthouse_config_file }}

      - name: Show current directory contents
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents of the current directory:"
          ls -la
          echo "Contents of the .unlighthouse directory (if it exists):"
          ls -la .unlighthouse || echo ".unlighthouse directory not found"

      - name: Deploy to Netlify
        run: |
          echo "Deploying to Netlify..."
          netlify deploy --dir=.unlighthouse --build false --prod --message="Deploy Unlighthouse report from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
